// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM8n5G3ieunGPucg9fLW4599OXw-TXRAg',
    appId: '1:415365586429:web:01a36cc8e1e130d343cd94',
    messagingSenderId: '415365586429',
    projectId: 'women-safety-app-308d1',
    authDomain: 'women-safety-app-308d1.firebaseapp.com',
    storageBucket: 'women-safety-app-308d1.appspot.com',
    measurementId: 'G-243S9JBQZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmOSTT9KU9P1Bb3wccfrQJZb4vYVmQdIk',
    appId: '1:415365586429:android:7e8ca44109d7f7f443cd94',
    messagingSenderId: '415365586429',
    projectId: 'women-safety-app-308d1',
    storageBucket: 'women-safety-app-308d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPEvrckNJ9dfdTJzc4vEApmOSwyDVJn4Y',
    appId: '1:415365586429:ios:83a62ef6bb277c1f43cd94',
    messagingSenderId: '415365586429',
    projectId: 'women-safety-app-308d1',
    storageBucket: 'women-safety-app-308d1.appspot.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );
}
